### ISSUE TITLE
missing autoload.php file in vendors folder.

### ISSUE THREAD

**Issue by veerendra456** [pusher/realtime-notifications-tutorial#1]
I am trying to integrate Pusher API in localhost
In notification/index.php file, first line is: require(dirname(__FILE__).'/../vendor/autoload.php');
in downloaded files there is no vendor/autoload.php file.
I am not getting any issue and no output. 
any updated file is there? 
Or Am downloaded from wrong file location.
could you please update. 
Thanks in advance

**Comment by callum-oakley** [comment]
Have you run `composer install`? This should generate `vendor/autoload.php`. See [the composer docs](https://getcomposer.org/doc/01-basic-usage.md).
